version: '2'
services:
    diploma-app:
        image: diploma
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://diploma-postgresql:5432/diploma
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    diploma-postgresql:
        extends:
            file: postgresql.yml
            service: diploma-postgresql
